background #161616
foreground #d8d6d0

# tab bar
active_tab_foreground   #d8d6d0
active_tab_background   #161616
active_tab_font_style   bold
inactive_tab_foreground #8b8a85
inactive_tab_background #161616
tab_bar_background      #161616

selection_background #2c2c2a
selection_foreground #d8d6d0

cursor #d8d6d0
cursor_text_color #161616

color0  #2c2c2a
color8  #55544f
color1  #d8d6d0
color9  #d8d6d0
color2  #8b8a85
color10 #8b8a85
color3  #c9c7c1
color11 #c9c7c1
color4  #b9b8b2
color12 #b9b8b2
color5  #aaa8a3
color13 #aaa8a3
color6  #9a9994
color14 #9a9994
color7  #d8d6d0
color15 #d8d6d0
