background #141414
foreground #d9d9d9

# tab bar
active_tab_foreground   #d9d9d9
active_tab_background   #141414
active_tab_font_style   bold
inactive_tab_foreground #8c8c8c
inactive_tab_background #141414
tab_bar_background      #141414

selection_background #2b2b2b
selection_foreground #d9d9d9

cursor #d9d9d9
cursor_text_color #141414

color0  #1f1f1f
color8  #5a5a5a
color1  #d9d9d9
color9  #d9d9d9
color2  #8c8c8c
color10 #8c8c8c
color3  #c8c8c8
color11 #c8c8c8
color4  #b8b8b8
color12 #b8b8b8
color5  #a8a8a8
color13 #a8a8a8
color6  #999999
color14 #999999
color7  #d9d9d9
color15 #d9d9d9
